DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO STRING NOT NULL,
    TEXTO STRING NOT NULL,
    data_criacao TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);